core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:HomePage:index }

core_friendsgroup:
    path:     /
    defaults: { _controller: CoreBundle:FriendsGroup:index }

core_friendsgroup_creation:
    path:     /
    defaults: { _controller: CoreBundle:FriendsGroup:creation }
