core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:HomePage:index }

core_friendsgroup:
    path:     /groups
    defaults: { _controller: CoreBundle:FriendsGroup:index }

core_friendsgroup_creation:
    path:     /groups/create
    defaults: { _controller: CoreBundle:FriendsGroup:creation }

core_story_add:
    path:   /story/add
    defaults: {_controller: CoreBundle:Story:add}

boug_profile:
    path:   /profile/{username}
    defaults: {_controller : CoreBundle:Boug:bougProfile}

friends_get_boug_list_for_friends_search:
    path:   /friends/get-boug-list-for-friends-search
    defaults: {_controller: CoreBundle:Friends:getBougListForFriendsSearch}

friends_add_friend:
    path:   /friends/add-friend
    defaults: {_controller: CoreBundle:Friends:addFriend}

friends_friend_requests:
    path:   /friends/friend-requests
    defaults: {_controller: CoreBundle:Friends:friendRequests}

friends_accept_friend_request:
    path:   /friends/accept-friend-request
    defaults: {_controller: CoreBundle:Friends:acceptFriendRequest}

story_rate:
    path: /story/rate
    defaults: {_controller: CoreBundle:Story:rate}

story_give_opinion:
    path: /story/give-opinion
    defaults: {_controller: CoreBundle:Story:giveOpinion}