core_index:
    path:     /
    defaults: { _controller: CoreBundle:HomePage:index }

core_homepage:
    path:     /homepage
    defaults: { _controller: CoreBundle:HomePage:homePage }

core_friendsgroup:
    path:     /groups/{idFriendsGroup}
    defaults: { _controller: CoreBundle:FriendsGroup:index }

core_friendsgroup_creation:
    path:     /groups/create
    defaults: { _controller: CoreBundle:FriendsGroup:creation }

core_story_add:
    path:   /story/add
    defaults: {_controller: CoreBundle:Story:add}

friends_get_user_friends_list:
    path:   /friends/get-user-friends-usernames-list
    defaults: {_controller: CoreBundle:Friends:getUsernamesOfFriendsOfUser}

friends_get_boug_list:
    path:   /friends/get-boug-list
    defaults: {_controller: CoreBundle:Friends:getBougList}

friends_add_friend:
    path:   /friends/add-friend
    defaults: {_controller: CoreBundle:Friends:addFriend}

friends_friend_requests:
    path:   /friends/friend-requests
    defaults: {_controller: CoreBundle:Friends:friendRequests}

friends_accept_friend_request:
    path:   /friends/accept-friend-request
    defaults: {_controller: CoreBundle:Friends:acceptFriendRequest}

story_rate:
    path: /story/rate
    defaults: {_controller: CoreBundle:Story:rate}



