core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:HomePage:index }

core_friendsgroup:
    path:     /groups
    defaults: { _controller: CoreBundle:FriendsGroup:index }

core_friendsgroup_creation:
    path:     /groups/create
    defaults: { _controller: CoreBundle:FriendsGroup:creation }

core_story_add:
    path:   /story/add
    defaults: {_controller: CoreBundle:Story:add}

friends_get_boug_list:
    path:   /friends/get-boug-list
    defaults: {_controller: CoreBundle:Friends:getBougList}

friends_add_friend:
    path:   /friends/add-friend
    defaults: {_controller: CoreBundle:Friends:addFriend}