fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:HomePage:index }

core_friendsgroup:
    path:     /groups
    defaults: { _controller: CoreBundle:FriendsGroup:index }

core_friendsgroup_creation:
    path:     /groups/create
    defaults: { _controller: CoreBundle:FriendsGroup:creation }

core_story_add:
    path:   /story/add
    defaults: {_controller: CoreBundle:Story:add}

fos_user_registration_confirmed:
    path: /registration/confirmed
    defaults: { _controller: CoreBundle:HomePage:index }


