# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    core.form.registration:
        class: CoreBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: core_user_registration }