<?php

namespace CoreBundle\Repository;

/**
 * BougStoryReadAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BougStoryReadAccessRepository extends \Doctrine\ORM\EntityRepository
{
	public function getStoryAccessForBoug($boug, $story)
	{
		return $this
            ->createQueryBuilder('bsra')
            ->where('bsra.story = :story')
            ->andWhere('bsra.boug = :boug')
            ->setParameter('story', $story)
            ->setParameter('boug', $boug)
            ->getQuery()
            ->getOneOrNullResult();
	}
}
