<?php

namespace CoreBundle\Repository;

/**
 * BougStoryReadAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BougStoryReadAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
