<?php

namespace CoreBundle\Repository;

/**
 * BougRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BougRepository extends \Doctrine\ORM\EntityRepository
{
	public function getBougsByPaternSearched($nameSearched)
    {
        return $this
            ->createQueryBuilder('b')
            ->where('b.username LIKE :nameSearched')
            ->setParameter('nameSearched', '%'.$nameSearched.'%')
            ->getQuery()
            ->getResult();
    }
}