<?php

namespace CoreBundle\Repository;

/**
 * BougStoryIsCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BougStoryIsCharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
