<?php

namespace CoreBundle\Repository;

/**
 * BougRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BougRepository extends \Doctrine\ORM\EntityRepository
{
}
