<?php

namespace CoreBundle\Repository;

/**
 * BougStoryIsCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BougStoryIsCharacterRepository extends \Doctrine\ORM\EntityRepository
{
	public function getIsCharacterForBoug($boug, $story)
	{
		return $this
            ->createQueryBuilder('bsic')
            ->where('bsic.story = :story')
            ->andWhere('bsic.boug = :boug')
            ->setParameter('story', $story)
            ->setParameter('boug', $boug)
            ->getQuery()
            ->getOneOrNullResult();
	}
}
