<?php

namespace CoreBundle\Repository;

/**
 * FriendsGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendsGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
